/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HarvestRouteImport } from './routes/harvest'
import { Route as CuringRouteImport } from './routes/curing'
import { Route as IndexRouteImport } from './routes/index'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestRoute = HarvestRouteImport.update({
  id: '/harvest',
  path: '/harvest',
  getParentRoute: () => rootRouteImport,
} as any)
const CuringRoute = CuringRouteImport.update({
  id: '/curing',
  path: '/curing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/curing': typeof CuringRoute
  '/harvest': typeof HarvestRoute
  '/journal': typeof JournalRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/curing': typeof CuringRoute
  '/harvest': typeof HarvestRoute
  '/journal': typeof JournalRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/curing': typeof CuringRoute
  '/harvest': typeof HarvestRoute
  '/journal': typeof JournalRoute
  '/reports': typeof ReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/curing' | '/harvest' | '/journal' | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/curing' | '/harvest' | '/journal' | '/reports'
  id: '__root__' | '/' | '/curing' | '/harvest' | '/journal' | '/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuringRoute: typeof CuringRoute
  HarvestRoute: typeof HarvestRoute
  JournalRoute: typeof JournalRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvest': {
      id: '/harvest'
      path: '/harvest'
      fullPath: '/harvest'
      preLoaderRoute: typeof HarvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curing': {
      id: '/curing'
      path: '/curing'
      fullPath: '/curing'
      preLoaderRoute: typeof CuringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuringRoute: CuringRoute,
  HarvestRoute: HarvestRoute,
  JournalRoute: JournalRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
