
ALTER TABLE public.movements
  ADD COLUMN IF NOT EXISTS destination TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS comment1 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS comment2 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS adjustment_validation BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS stamp_used TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stamp_type TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS additional_comments TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS elevated_update BOOLEAN NOT NULL DEFAULT false;
